country = {
    "Afeganistão": "Afghanistan",
    "África do Sul": "South Africa",
    "Alemanha, República Democrática": "Germany",
    "Angola": "Angola",
    "Anguilla": "Anguilla",
    "Antígua e Barbuda": "Antigua and Barbuda",
    "Argentina": "Argentina",
    "Aruba": "Aruba",
    "Austrália": "Australia",
    "Áustria": "Austria",
    "Bahamas": "Bahamas",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Barein": "Bahrain",
    "Bélgica": "Belgium",
    "Belice": "Belize",
    "Benin": "Benin",
    "Bolívia": "Bolivia",
    "Bósnia-Herzegovina": "Bosnia",
    "Brasil": "Brazil",
    "Bulgária": "Bulgaria",
    "Cabo Verde": "Republic of Cabo Verde",
    "Camarões": "Cameroon",
    "Canadá": "Canada",
    "Catar": "Qatar",
    "Chile": "Chile",
    "China": "China",
    "Chipre": "Cyprus",
    "Cingapura": "Singapore",
    "Cocos (Keeling), Ilhas": "Cocos (Keeling) Islands",
    "Colômbia": "Colombia",
    "Comores": "Comoros",
    "Congo": "Congo",
    "Coreia, Republica Sul": "South Korea",
    "Costa do Marfim": "Côte d'Ivoire",
    "Costa Rica": "Costa Rica",
    "Croácia": "Croatia",
    "Cuba": "Cuba",
    "Curaçao": "Curacao",
    "Dinamarca": "Denmark",
    "Dominica": "Dominica",
    "Rússia": "Russia",
    "El Salvador": "El Salvador",
    "Emirados Arabes Unidos": "Saudi Arabia",
    "Equador": "Ecuador",
    "Eslovaca, Republica": "Slovakia",
    "Espanha": "Spain",
    "Estados Unidos": "US",
    "Estônia": "Estonia",
    "Filipinas": "Philippines",
    "Finlândia": "Finland",
    "França": "France",
    "Gana": "Ghana",
    "Gibraltar": "Gibraltar",
    "Granada": "Grenada",
    "Grécia": "Greece",
    "Guatemala": "Guatemala",
    "Guiana": "Guyana",
    "Guiana Francesa": "French Guiana",
    "Guine Bissau": "Guinea-Bissau",
    "Guine Equatorial": "Equatorial Guinea",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Hong Kong": "Hong Kong",
    "Hungria": "Hungary",
    "Ilha de Man": "Isle of Man",
    "Ilhas Virgens": "Virgin Islands",
    "India": "India",
    "Indonésia": "Indonesia",
    "Irã": "Iran",
    "Iraque": "Iraq",
    "Irlanda": "Ireland",
    "Itália": "Italy",
    "Jamaica": "Jamaica",
    "Japão": "Japan",
    "Jordânia": "Jordan",
    "Letônia": "Latvia",
    "Líbano": "Lebanon",
    "Libéria": "Liberia",
    "Luxemburgo": "Luxembourg",
    "Malásia": "Malaysia",
    "Malta": "Malta",
    "Marshall, Ilhas": "Marshall Islands",
    "Mauritânia": "Mauritania",
    "México": "Mexico",
    "Moçambique": "Mozambique",
    "Montenegro": "Montenegro",
    "Namibia": "Namibia",
    "Nicaragua": "Nicaragua",
    "Nigéria": "Nigeria",
    "Noruega": "Norway",
    "Nova Caledônia": "New Caledonia",
    "Nova Zelândia": "New Zealand",
    "Omã": "Oman",
    "Países Baixos": "Netherlands",
    "Panamá": "Panama",
    "Paraguai": "Paraguay",
    "Peru": "Peru",
    "Polônia": "Poland",
    'Netherlands Antilles': "Caribbean Netherlands",
    "Antilhas Holandesas": "Caribbean Netherlands",
    'Bellice': "Belize",
    'Bosnia Herzegovina': "Bosnia and Herzegovina",
    'Cape Green': "Cape Verde",
    '"Cayman, Islands"': 'Cayman Islands',
    '"Cayman, Ilhas"': "Cayman Islands",
    "Cayman, Ilhas": "Cayman Islands",
    'Ivory Coast': "Côte d'Ivoire",
    'Grenade': "Grenada",
    'Guinea Bissau': "Guinea-Bissau",
    '"Marshall, Islands"': 'Marshall Islands',
    'Porto Rico': "Puerto Rico",
    'Quênia': "Kenya",
    'Reino Unido': "United Kingdom",
    'República Dominicana': "Dominican Republic",
    'São Tomé e Príncipe': "Sao Tome and Principe",
    'São Vicente e Granadinas': "Saint Vincent and the Grenadines",
    'Serra Leoa': "Sierra Leone",
    'Singapura': "Singapore",
    'Suazilândia': "Eswatini",
    'Suécia': "Sweden",
    'Suíça': "Switzerland",
    'Tailândia': "Thailand",
    'Taiwan (FORMOSA)': "Taiwan",
    "Tcheca, República": 'Czech Republic',
    'Trinidade Tobago': "Trinidad and Tobago",
    'Turquia': "Turkey",
    'Uruguai': "Uruguay",
    'Vietnã': "Vietnam"
}
